- hosts: all
  become: true
  tasks:
    - name: Update cache
      apt: update_cache=true

    - name: Grab unix kernel release
      shell: uname -r | xargs
      register: kernel_release

    - name: Grab lsb release
      shell: lsb_release -cs | xargs
      register: lsb_release

    - name: Fetch recommended packages
      apt: name={{item}} state=present
      with_items:
        - linux-image-extra-{{ kernel_release.stdout }}
        - linux-image-extra-virtual
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable

    - name: Update cache again
      apt: update_cache=true

    - name: Finally! Install Docker-CE
      apt: name=docker-ce state=present
